title: Mason Schick # your name (or website title) here
logo: "/images/ProfilePhoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <br><br>
  <a href="https://www.linkedin.com/in/mason-schick/">LinkedIn</a> 
  <br><br>
  <a href="images/MasonSchick_Resume_4-1-24.pdf" class="btn btn--info">Resume</a>  
  <br><br>
  <a href="https://www.GitHub.com/masonschick/">GitHub</a>  
  <br>
  
theme: jekyll-theme-minimal
